"""Index every fit on disk: where it is, what it was run with, what it scored.

`results/` is gitignored, so the checkpoints themselves are not in the repository and a
tracked index is the only durable trace of what exists locally. This reads the npz files
rather than a hand-kept list, so it cannot drift from them - re-run it after a fit and
commit the diff.

Records only what the files record. Runs written before `core/provenance.py` existed have
no command line, and that is printed as `not recorded` rather than reconstructed: a
plausible-looking guess at an argv is worse than a blank, because the parameters that
matter most here - wa, lag_taus, seed - are exactly the ones that were never saved.

  python analysis/runs.py              # rewrite RUNS.md
  python analysis/runs.py --print      # to stdout, leave the file alone
"""
import _path  # noqa: F401  - puts the sibling code folders on sys.path
import os, glob, json, argparse, datetime
import numpy as np

import provenance
from paths import RESULTS

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def scores_for(tag, z):
    """Every realised score known for a tag: the one in the npz, plus any length the
    rescore sidecar holds. -> {label: dict}, oldest measurement first is not meaningful
    here so they are sorted by length."""
    out = {}
    if "sim" in z:
        sec = _scalar(z, "realise_seconds")
        lab = "?" if sec is None or sec != sec else f"{int(round(sec))}s"
        out[lab] = dict(sim=float(z["sim"]), sim_sd=float(_scalar(z, "sim_sd", 0.0)),
                        gap=float(_scalar(z, "gap", float("nan"))),
                        field_rank=float(_scalar(z, "field_rank", float("nan"))),
                        draws=int(_scalar(z, "draws", 0)))
    sp = os.path.join(RESULTS, f"scores_{tag}.json")
    if os.path.exists(sp):
        try:
            out.update(json.load(open(sp)))
        except (ValueError, OSError):
            pass
    return dict(sorted(out.items(),
                       key=lambda kv: float(kv[0][:-1]) if kv[0][:-1].isdigit() else 0))


def _scalar(z, key, default=None):
    if key not in z:
        return default
    v = z[key]
    try:
        return v.item() if v.size == 1 else v
    except (AttributeError, ValueError):
        return v


def _num(v, fmt="{:g}"):
    return "-" if v is None else fmt.format(v) if isinstance(v, float) else str(v)


def _when(path):
    return datetime.datetime.fromtimestamp(os.path.getmtime(path)).strftime("%Y-%m-%d %H:%M")


def _rel(path):
    return os.path.relpath(path, ROOT)


def torchfits():
    """The gradient fits: results/torchfit_<tag>.npz, with their iteration dumps."""
    out = []
    for f in glob.glob(os.path.join(RESULTS, "torchfit_*.npz")):
        tag = os.path.basename(f)[len("torchfit_"):-len(".npz")]
        if "_it" in tag and tag.rsplit("_it", 1)[1].isdigit():
            continue                                   # an iteration dump, not a run
        try:
            z = np.load(f, allow_pickle=True)
        except (OSError, ValueError) as e:
            out.append((os.path.getmtime(f), tag, None, str(e), f))
            continue
        dumps = sorted(int(os.path.basename(d).rsplit("_it", 1)[1][:-4])
                       for d in glob.glob(os.path.join(RESULTS, f"torchfit_{tag}_it*.npz")))
        out.append((os.path.getmtime(f), tag, z, dumps, f))
    return sorted(out, key=lambda r: r[0])


def solves():
    """The convex solves, which are also the bases the gradient fits start from."""
    out = []
    for f in sorted(glob.glob(os.path.join(RESULTS, "xspec_*.npz"))):
        try:
            z = np.load(f, allow_pickle=True)
        except (OSError, ValueError):
            continue
        out.append((os.path.getmtime(f), os.path.basename(f)[len("xspec_"):-len(".npz")],
                    z, f))
    return sorted(out, key=lambda r: r[0])


def _command(z):
    pr = provenance.read(z)
    if not pr:
        return ["command: *not recorded*"]
    lines = [f"command: `{pr['argv']}`",
             f"at: {pr['run_at']} · commit: `{pr['git_commit'] or 'unknown'}`"]
    if pr.get("args"):
        lines.append(f"args: `{json.dumps(pr['args'], sort_keys=True)}`")
    return lines


def render():
    L = ["# Runs",
         "",
         "Generated by `analysis/runs.py` from the npz files in `results/`, which is",
         "gitignored - the paths below are local. Re-run it after a fit.",
         "",
         f"Last generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}",
         ""]

    tf = torchfits()
    L += [f"## Gradient fits through the simulation ({len(tf)})", "",
          "`fit/torch_fit.py`. Oldest first.", ""]
    for mt, tag, z, dumps, f in tf:
        L.append(f"### {tag}")
        if z is None:
            L += [f"`{_rel(f)}` · {_when(f)} · unreadable: {dumps}", ""]
            continue
        rep = os.path.join(RESULTS, tag)
        head = [f"`{_rel(f)}`", _when(f)]
        if os.path.isdir(rep):
            head.append(f"report `{_rel(rep)}/`")
        if dumps:
            head.append("dumps at " + ", ".join(str(d) for d in dumps))
        L.append(" · ".join(head))

        p = [f"ref **{_scalar(z,'ref')}**",
             f"{_num(_scalar(z,'seconds'))} s",
             f"init {_scalar(z,'init')}",
             f"amp {_num(_scalar(z,'amp'))}",
             f"nl_flux {_num(_scalar(z,'nl_flux'))}",
             f"nl_adv {_num(_scalar(z,'nl_adv'))}"]
        if "learn_maps" in z:
            p.append(f"learn_maps {_num(_scalar(z,'learn_maps'))}")
        p += [f"Ld {_num(_scalar(z,'Ld'))}", f"maps_scale {_num(_scalar(z,'maps_scale'))}"]
        L.append(" · ".join(p))

        n = len(z["hist"]) if "hist" in z else None
        bs, bi = _scalar(z, "best_sim"), _scalar(z, "best_iter")
        L.append(f"{n if n is not None else '?'} iterations · "
                 f"best_sim {'-' if bs is None else f'{bs:+.4f}'} at iteration {bi}")
        L += _command(z)
        L.append("")

    sv = solves()
    L += [f"## Convex solves ({len(sv)})", "",
          "`fit/best_fit.py`, writing `results/xspec_<tag>.npz`. These are also the bases",
          "`torch_fit.py --ref` selects. One row each, oldest first; `cmd` says whether the",
          "file carries its own command line.", "",
          "| tag | pieces | regions | split | band Hz | frame_s | impulse | nfreq | "
          "realised | written | cmd |",
          "|---|---|---|---|---|---|---|---|---|---|---|"]
    stamped = []
    for mt, tag, z, f in sv:
        b = z["band"] if "band" in z else None
        fs = float(z["frame_s"]) if "frame_s" in z else float("nan")
        pr = provenance.read(z)
        if pr:
            stamped.append((tag, pr))
        L.append("| `{}` | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} |".format(
            tag,
            z["profiles"].shape[0] if "profiles" in z else "?",
            _scalar(z, "regions", "-"), _scalar(z, "split", "-"),
            "-" if b is None else f"{b[0]:g}-{b[1]:g}",
            "-" if fs != fs else f"{fs:.5g}",
            _scalar(z, "impulse_frames", "-"), _scalar(z, "nfreq", "-"),
            " / ".join(f"{v['sim']:+.4f}±{v['sim_sd']:.4f} @{k}"
                       for k, v in scores_for(tag, z).items()) or "-",
            _when(f), "yes" if pr else "–"))
    L.append("")
    if stamped:
        L += ["### Commands, where recorded", ""]
        for tag, pr in stamped:
            L += [f"**{tag}** — `{pr['argv']}`",
                  f"  {pr['run_at']} · commit `{pr['git_commit'] or 'unknown'}`", ""]
    return "\n".join(L).rstrip() + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--print", action="store_true", dest="to_stdout",
                    help="write to stdout instead of RUNS.md")
    ap.add_argument("--out", default=os.path.join(ROOT, "RUNS.md"))
    a = ap.parse_args()
    text = render()
    if a.to_stdout:
        print(text, end="")
        return
    open(a.out, "w").write(text)
    print(f"  wrote {_rel(a.out)}  ({len(text.splitlines())} lines)")


if __name__ == "__main__":
    main()
